#Can bullet break glass block
#子弹可以击碎玻璃块
shot_break_glass = true
#Can bullet active redstone signal when hit 'Target Block'
#子弹击中‘标靶方块’时激活其红石信号
shot_active_redstone = true
#The maximum tick value that the bullet entity can exist, if it exceeds this value, the bullet entity will be destroyed no matter what, in general you do not need to change this value
#子弹实体能存在的最大tick值，如果超过这个值，则无论如何子弹实体都会被销毁，一般情况下你不需要改动这个值
#Range: 10 ~ 500
max_bullet_life_length = 100
#Creative use ammo
#创造模式消耗子弹
creative_mode_use_ammo = false
#Enable vending machine
#启用自动售货机
enable_vending_machine = true
#Vending machine print deal credit ticket for player
#自动售货机交易完成后为玩家打印交易凭据
print_deal_credit = false
#Enable head shot
#启用爆头判定
enable_head_shot = true
#Enable knock back
#启用子弹击退
enable_knock_back = true
#Set the headshot parameters. The following are the parameters of the registered minecraft original creatures.
#You just need to add a custom project that mimics the existing project format.
#First parameter: headshot damage multiplier(1.0 ~ 5.0)
#Second parameter: the size of the head bounding box (which is a cube) relative to the original mob bounding box
#Third parameter: the height of the center of the head bounding box relative to the original mob bounding box (0 for the bottom of the foot, 1 for the top of the head)
#配置headshot参数，以下是已经注册好的minecraft原版生物的参数，
#你只需要仿照已有的项目格式添加自定义项目就行了。
#第一个参数：headshot伤害倍数（1.0 ~ 5.0）
#第二个参数：头部碰撞箱（这是一个正方体）相对于原生物碰撞箱的大小
#第三个参数：头部碰撞箱中心相对于相对于原生物碰撞箱的高度（脚底为0，头顶为1）
headshot_modify = ["minecraft:zombie=2.0,0.75,0.8", "minecraft:husk=2.0,0.8,0.82", "minecraft:zombified_piglin=2.0,0.85,0.8", "minecraft:piglin_brute=2.0,0.85,0.8", "minecraft:piglin=2.0,0.85,0.8", "minecraft:enderman=2.0,0.85,0.825", "minecraft:drowned=2.0,0.75,0.8", "minecraft:zombie_villager=2.0,0.9,0.8", "minecraft:pillager=2.0,0.9,0.8", "minecraft:evoker=2.0,0.9,0.8", "minecraft:villager=1.5,0.9,0.8", "minecraft:wandering_trader=1.5,0.9,0.8", "minecraft:vindicator=2.0,0.9,0.8", "minecraft:witch=2.0,0.9,0.8", "minecraft:blaze=2.0,0.75,0.8", "minecraft:skeleton=2.0,0.75,0.8", "minecraft:player=1.5,0.7,0.82", "minecraft:iron_golem=1.5,0.5,0.82", "minecraft:snow_golem=1.5,0.9,0.8", "minecraft:vex=2.0,0.9,0.65", "minecraft:warden=2.0,1.0,0.8", "minecraft:creeper=2.0,0.8,0.75"]

